version: 0.0
phases:
  pre_build:
    commands:
      - echo "Entered the pre-build phase"
  build:
    commands:
      - echo "Entered the build phase"
  post_build:
    commands:
      - echo "Entered the post-build phase"
artifacts:
  files:
    - '**/*'
